name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: conduit
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm ci

      - name: Install backend deps and prep DB
        run: |
          cd app
          npm ci
          echo 'DATABASE_URL="postgresql://postgres:postgres@localhost:5432/conduit?schema=public"' > .env
          npx prisma db push

      - name: Build & start backend
        run: |
          cd app
          npm run build
          nohup npm start &

      - name: Wait for API
        run: |
          for i in {1..20}; do
            if curl -s http://localhost:3000/api/tags >/dev/null; then
              echo "API ready"; break; fi
            echo "Waiting…"; sleep 3;
          done

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npx playwright test

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report